apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: gsc-cluster
  namespace: kafka
spec:
  kafka:
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: '3.1'
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
        ephemeral-storage: 500Mi
    storage:
      type: ephemeral
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: route
        tls: true
    version: 3.1.0
    replicas: 3
  entityOperator:
    topicOperator: {}
    userOperator: {}
  zookeeper:
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
        ephemeral-storage: 500Mi
    storage:
      type: ephemeral
    replicas: 3
