apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: gsc-topic
  labels:
    strimzi.io/cluster: gsc-cluster
  namespace: kafka
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
